name: Parse IFP
on:
  push:
    paths:
      - 'input/*.ifp'
  workflow_dispatch:

jobs:
  parse:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: git make gcc

      - name: Build anim_parser
        shell: msys2 {0}
        run: |
          git clone https://github.com/Daniel-Cortez/sa-anim-parser.git
          cd sa-anim-parser
          make

      - name: Parse IFP file
        shell: msys2 {0}
        run: |
          ./sa-anim-parser/anim_parser.exe input/python.ifp > output/python_parsed.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: parsed-animation
          path: output/python_parsed.txt
